import = [
	"~/.config/alacritty/themes/themes/dracula_plus.toml"
]

[env]

[window]
padding = {x = 10, y = 10}
startup_mode = "Fullscreen"

option_as_alt = "Both"

[scrolling]

[keyboard]
bindings = [
]

[font.normal]
family = "MesloLGS NF"
