#!/usr/bin/env zsh

FONT_FACE="Hack Nerd Font"
PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --bar \
  height=32 \
  color=0x00000000 \
  margin=0 \
  sticky=on \
  padding_left=25 \
  padding_right=25 \
  notch_width=188 \
  display=main

sketchybar --default \
  background.color=0x323437 \
  background.corner_radius=5 \
  background.padding_right=5 \
  background.height=26 \
  background.drawing=on \
  icon.font="$FONT_FACE:Bold:16.0" \
  icon.color=0xffffffff \
  icon.padding_left=4 \
  icon.padding_right=4 \
  label.font="$FONT_FACE:Bold:13.0" \
  label.color=0xffffffff \
  label.padding_left=0 \
  label.padding_right=5

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item chevron left \
  --set chevron icon= \
    background.color=0x323437 \
    background.height=26 \
    background.drawing=on \
    label.drawing=off \
  --add item front_app left \
  --set front_app \
    background.color=0x323437 \
    background.height=26 \
    background.drawing=on \
    icon.drawing=off \
    script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

##### Aerospace Integration #####
sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
          background.color=0x44ffffff \
          background.corner_radius=5 \
          background.height=20 \
          background.drawing=off \
          label="$sid" \
          click_script="aerospace workspace $sid" \
          script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
  --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
  --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change \
  --add item battery right \
  --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
